@WebApplication_HibaVonal_HostAddress = https://localhost:7194

GET {{WebApplication_HibaVonal_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{WebApplication_HibaVonal_HostAddress}}/orders

###
